package com.CDC.GuardiaBackend.Enums;

public enum ProtocolGroup {
    CARDIOVASCULAR,
    CIRUGIA,
    ENDOCRINOMETABOLICO,
    GASTROENTEROLOGIA,
    GINECOOBSTETRICIA,
    HOMEOSTASIS,
    INFECTOLOGIA,
    NEFROLOGIA,
    NEUMONOLOGIA,
    NEUROLOGIA,
    OTORRINOLARINGOLOGIA,
    PROCEDIMIENTO,
    TOXICOLOGIA,
    TRAUMATOLOGIA,
    UROLOGIA,
}