package com.CDC.GuardiaBackend.Enums;

public enum Specialties {
    CARDIOVASCULAR,
    CIRUGIA,
    ENDOCRINOMETABOLICO,
    GASTROENTEROLOGIA,
    GENERALISTA,
    GINECOOBSTETRICIA,
    INFECTOLOGIA,
    CLINICA,
    NEFROLOGIA,
    NEUMONOLOGIA,
    NEUROLOGIA,
    OTORRINOLARINGOLOGIA,
    TOXICOLOGIA,
    TRAUMATOLOGIA,
    UROLOGIA,
}
